on:
  push:
    branches:
      - develop
name: create-pull-request workflow
jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
        
      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main"
          pr_body: "An automated PR"
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

